-- ============================================================
-- 0014 — WHO IS ALLOWED TO SAY SOMETHING HAPPENED
--
-- Three holes found by probing 0013 against real Postgres, not by reading it:
--
--   1. im_notify is security definer and only checked that the athlete was on
--      the coach's roster. An athlete could therefore call it directly and
--      write any title and body they liked into their own coach's feed —
--      "Coach, call me now" with a phone number that is not theirs. The roster
--      check answers "is this about someone you coach"; nothing answered "are
--      you allowed to speak at all".
--   2. im_record_delivery had no authorisation check whatsoever. Any signed-in
--      user could mark any delivery on any notification as delivered, which
--      would make the delivery log — the thing this slice uses to avoid
--      claiming success it cannot prove — lie.
--   3. The digest and alert jobs run as the service role, which has no
--      auth.uid(). im_coach_roster resolved the caller to auth.uid() and
--      required im_is_staff(), so a job asking for a coach's roster got zero
--      rows and every digest would have been silently empty. The job would
--      have reported success and sent nothing.
--
-- The fix for all three is the same idea: name the service role explicitly
-- rather than leaving it to fall through a check meant for people.
-- ============================================================


-- The server-side identity: cron jobs, webhooks, migrations. It has no
-- auth.uid() because no person is asking. Deliberately narrow — it is true
-- only when there is no signed-in subject AND the JWT says service_role, so a
-- signed-in user cannot reach it by clearing a claim.
create or replace function im_is_service()
returns boolean language sql stable set search_path = public as $$
  select auth.uid() is null and coalesce(auth.role(), '') = 'service_role';
$$;

comment on function im_is_service is
  'True for the server-side service role only. Never true for a signed-in user.';


-- ------------------------------------------------------------
-- 1. Only the server may put words in a coach's feed.
-- ------------------------------------------------------------

create or replace function im_notify(
  p_user          uuid,
  p_kind          im_notification_kind,
  p_priority      text,
  p_title         text,
  p_body          text,
  p_href          text,
  p_dedupe_key    text,
  p_athlete       uuid default null,
  p_signal_kind   text default null,
  p_deliver_after timestamptz default null,
  p_payload       jsonb default null,
  p_channels      text[] default array['in_app']
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
  v_channel text;
begin
  -- notifications are generated by jobs from canonical roster signals; they
  -- are never composed by a person, so nobody signed in may call this
  if not (im_is_service() or im_is_admin() or auth.uid() is null) then
    raise exception 'Notifications are generated by Iron Miles, not sent by users.';
  end if;

  -- an athlete-specific notification only ever goes to that athlete's coach
  if p_athlete is not null and not exists (
    select 1 from coach_athlete_links l
     where l.athlete_id = p_athlete and l.coach_id = p_user and l.status = 'active'
  ) then
    raise exception 'That athlete is not on that coach''s roster.';
  end if;

  insert into notifications (
    user_id, notification_kind, priority, athlete_id, signal_kind,
    kind, title, body, href, dedupe_key, deliver_after, payload)
  values (
    p_user, p_kind, p_priority, p_athlete, p_signal_kind,
    coalesce(p_signal_kind, p_kind::text), p_title, p_body, p_href,
    p_dedupe_key, p_deliver_after, p_payload)
  on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
  returning id into v_id;

  -- already told them; not an error, just nothing to do
  if v_id is null then return null; end if;

  foreach v_channel in array p_channels loop
    insert into notification_deliveries (notification_id, user_id, channel)
    values (v_id, p_user, v_channel::im_channel)
    on conflict (notification_id, channel) do nothing;
  end loop;

  return v_id;
end $$;


-- ------------------------------------------------------------
-- 2. Only the delivery worker may say a delivery happened.
--
-- This function is the only evidence the product has that anything actually
-- left the building. If a user can write to it, "delivered" means nothing.
-- ------------------------------------------------------------

create or replace function im_record_delivery(
  p_delivery uuid,
  p_state    im_delivery_state,
  p_detail   text default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not (im_is_service() or im_is_admin() or auth.uid() is null) then
    raise exception 'Delivery outcomes are recorded by the delivery worker.';
  end if;

  update notification_deliveries
     set state = p_state,
         detail = p_detail,
         attempts = attempts + 1,
         attempted_at = now(),
         delivered_at = case when p_state = 'delivered' then now() else delivered_at end
   where id = p_delivery;
end $$;


-- ------------------------------------------------------------
-- 3. The digest job must be able to read the roster it is summarising.
--
-- Unchanged in every other respect: a coach passing another coach's id still
-- gets their own roster. The only new caller is the service role, which must
-- name the coach explicitly because it has no identity of its own.
-- ------------------------------------------------------------

create or replace function im_coach_roster(
  p_coach uuid default null,
  p_today date default current_date
)
returns table (
  athlete_id            uuid,
  full_name             text,
  avatar_url            text,
  joined_at             timestamptz,

  programme_id          uuid,
  programme_name        text,
  programme_end_date    date,
  block_name            text,
  phase                 im_phase,
  week_no               integer,
  total_weeks           integer,

  planned_this_week     integer,
  completed_this_week   integer,
  planned_four_weeks    integer,
  completed_four_weeks  integer,

  missed_fourteen_days  integer,
  missed_key_name       text,
  missed_key_date       date,

  last_completed_date   date,
  last_completed_name   text,
  next_session_date     date,
  next_session_name     text,
  future_sessions       integer,

  checkin_week_start    date,
  checkin_submitted_at  timestamptz,
  checkin_attention     im_attention,
  checkin_reasons       text[],
  checkin_reviewed_at   timestamptz,
  checkin_fatigue       smallint,
  checkin_soreness      smallint,
  checkin_pain          text,

  race_id               uuid,
  race_name             text,
  race_date             date,
  goal_event_type       im_event_type,

  unread_from_athlete   integer,
  recent_adaptations    integer
)
language sql stable security definer set search_path = public as $$
with
  -- who the caller may see. A coach passing another coach's id gets their
  -- own roster, not that coach's: the link table is the authority, never
  -- the argument.
  me as (
    select case
             when (im_is_admin() or im_is_service()) and p_coach is not null then p_coach
             else auth.uid()
           end as coach_id
  ),
  roster as (
    select l.athlete_id, l.started_at
      from coach_athlete_links l, me
     where l.coach_id = me.coach_id
       and l.status = 'active'
       and (im_is_staff() or im_is_service())
  ),
  -- the athlete's live programme, and where they are in it
  prog as (
    select p.athlete_id, p.id, p.name, p.end_date,
           (select count(*)::integer from program_weeks w where w.program_id = p.id) total_weeks
      from programs p
      join roster r on r.athlete_id = p.athlete_id
     where p.status = 'active'
  ),
  this_week as (
    select w.program_id, w.id week_id, w.program_week_no, b.name block_name, b.phase
      from program_weeks w
      join program_blocks b on b.id = w.block_id
      join prog on prog.id = w.program_id
     where p_today >= w.start_date and p_today < w.start_date + 7
  ),
  -- every count over sessions comes from one pass, not one query each
  sessions as (
    select
      s.athlete_id,
      count(*) filter (
        where s.date >= date_trunc('week', p_today)::date
          and s.date <= p_today and s.type <> 'rest')::integer planned_week,
      count(*) filter (
        where s.date >= date_trunc('week', p_today)::date
          and s.date <= p_today and s.type <> 'rest' and s.status = 'completed')::integer done_week,
      count(*) filter (
        where s.date >= p_today - 27 and s.date <= p_today and s.type <> 'rest')::integer planned_month,
      count(*) filter (
        where s.date >= p_today - 27 and s.date <= p_today
          and s.type <> 'rest' and s.status = 'completed')::integer done_month,
      count(*) filter (
        where s.date >= p_today - 13 and s.date <= p_today
          and s.type <> 'rest' and s.status = 'missed')::integer missed_fortnight,
      count(*) filter (where s.date >= p_today and s.status = 'scheduled')::integer future_count
    from scheduled_workouts s
    join roster r on r.athlete_id = s.athlete_id
    group by s.athlete_id
  )
select
  pr.id,
  pr.full_name,
  pr.avatar_url,
  r.started_at,

  prog.id,
  prog.name,
  prog.end_date,
  tw.block_name,
  tw.phase,
  tw.program_week_no::integer,
  prog.total_weeks,

  coalesce(sess.planned_week, 0),
  coalesce(sess.done_week, 0),
  coalesce(sess.planned_month, 0),
  coalesce(sess.done_month, 0),

  coalesce(sess.missed_fortnight, 0),
  key_missed.name,
  key_missed.date,

  last_done.date,
  last_done.name,
  next_up.date,
  next_up.name,
  coalesce(sess.future_count, 0),

  ci.week_start,
  ci.submitted_at,
  ci.attention_level,
  ci.attention_reasons,
  ci.reviewed_by_coach_at,
  ci.fatigue,
  ci.soreness,
  nullif(btrim(coalesce(ci.pain_or_niggles, '')), ''),

  race.id,
  race.name,
  race.date,
  race.event_type,

  coalesce(msg.unread, 0)::integer,
  coalesce(adapt.recent, 0)::integer

from roster r
join profiles pr on pr.id = r.athlete_id
left join prog on prog.athlete_id = r.athlete_id
left join this_week tw on tw.program_id = prog.id
left join sessions sess on sess.athlete_id = r.athlete_id

-- a missed session worth naming: the hard ones, most recent first
left join lateral (
  select s.name, s.date
    from scheduled_workouts s
   where s.athlete_id = r.athlete_id
     and s.status = 'missed'
     and s.date >= p_today - 13
     and s.type in ('long_run','threshold','intervals','race_pace','hills','tempo','brick','race')
   order by s.date desc
   limit 1
) key_missed on true

left join lateral (
  select s.date, s.name
    from scheduled_workouts s
   where s.athlete_id = r.athlete_id and s.status = 'completed'
   order by s.date desc
   limit 1
) last_done on true

left join lateral (
  select s.date, s.name
    from scheduled_workouts s
   where s.athlete_id = r.athlete_id and s.status = 'scheduled' and s.date >= p_today
     and s.type <> 'rest'
   order by s.date, s.slot
   limit 1
) next_up on true

left join lateral (
  select c.* from checkins c
   where c.athlete_id = r.athlete_id
   order by c.week_start desc
   limit 1
) ci on true

left join lateral (
  select ra.id, ra.name, ra.date, g.event_type
    from goals g join races ra on ra.id = g.race_id
   where g.athlete_id = r.athlete_id and ra.date >= p_today
   order by ra.date
   limit 1
) race on true

-- messages reach an athlete through their thread with this coach
left join lateral (
  select count(*)::integer unread
    from messages m
    join message_threads th on th.id = m.thread_id
    cross join me
   where th.athlete_id = r.athlete_id
     and m.recipient_id = me.coach_id
     and m.read_at is null
) msg on true

-- what this coach changed for them lately, so the roster does not report a
-- deliberate adaptation as if it were a surprise
left join lateral (
  select count(*)::integer recent
    from session_revisions sr, me
   where sr.athlete_id = r.athlete_id
     and sr.changed_by = me.coach_id
     and sr.changed_at >= (p_today - 6)::timestamptz
     and sr.kind <> 'created'
) adapt on true

order by pr.full_name;
$$;

comment on function im_coach_roster is
  'One row of facts per athlete on the caller''s roster. Judgement lives in the domain layer.';
