import assert from 'node:assert/strict';
import { after, before, describe, it } from 'node:test';
import { createTestDatabase } from './harness.mjs';

/**
 * NOTIFICATIONS, AGAINST REAL POSTGRES
 *
 * The claim this slice makes is that a coach is told the right things, once,
 * and that nobody else can put words in their feed or forge a delivery
 * receipt. None of that can be established by reading the SQL — every
 * assertion below runs it.
 *
 * The matching in-memory assertions are src/lib/data/notification-parity.test.ts.
 */

let t, coachA, coachB, athleteA, athleteB, outsider;

before(async () => {
  t = await createTestDatabase();

  coachA = await t.signUp('coach.a@ironmiles.ie', 'Coach A');
  coachB = await t.signUp('coach.b@ironmiles.ie', 'Coach B');
  await t.setRole(coachA, 'coach');
  await t.setRole(coachB, 'coach');

  athleteA = await t.signUp('athlete.a@ironmiles.ie', 'Athlete A');
  athleteB = await t.signUp('athlete.b@ironmiles.ie', 'Athlete B');
  outsider = await t.signUp('outsider@ironmiles.ie', 'Outsider');

  await t.asService(
    `insert into coach_athlete_links (coach_id, athlete_id, status) values ($1,$2,'active'), ($3,$4,'active')`,
    [coachA, athleteA, coachB, athleteB]);
});

after(() => t.close());

const notify = (args) => t.asService(
  `select im_notify($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,null,$11) as id`, args);

describe('who may put words in a coach\'s feed', () => {
  it('lets the server write one', async () => {
    const { rows } = await notify([coachA, 'alert', 'attention', 'Athlete A — check-in flagged',
      'Check-in flagged: fatigue up.', `/coach/athletes/${athleteA}`,
      `checkin_flagged:${athleteA}:2026-08-24`, athleteA, 'checkin_flagged', null, ['in_app']]);
    assert.ok(rows[0].id, 'written');
  });

  it('refuses an athlete calling it directly', async () => {
    // security definer plus a roster check is not authorisation: the roster
    // check only asks who it is about, never who is asking
    const message = await t.expectRefused(athleteA,
      `select im_notify($1,'alert','urgent','Coach, ring me','On 08...','/coach','forge:1',$2,'checkin_flagged')`,
      [coachA, athleteA]);
    assert.match(message ?? '', /generated by Iron Miles/i);
  });

  it('refuses a coach hand-writing one for themselves', async () => {
    const message = await t.expectRefused(coachA,
      `select im_notify($1,'digest','urgent','Made up','body','/coach','forge:2')`, [coachA]);
    assert.ok(message, 'refused');
  });

  it('refuses a direct insert into the table', async () => {
    const message = await t.expectRefused(coachA,
      `insert into notifications (user_id, kind, title, body) values ($1,'alert','Made up','body')`,
      [coachA]);
    assert.ok(message, 'the policy holds even without the function');
  });

  it('refuses to tell a coach about an athlete who is not theirs', async () => {
    await assert.rejects(
      () => notify([coachA, 'alert', 'attention', 'Athlete B', 'body', '/coach',
        'cross:1', athleteB, 'checkin_flagged', null, ['in_app']]),
      /roster/i);
  });

  it('refuses an athlete whose link has ended', async () => {
    const past = await t.signUp('past@ironmiles.ie', 'Past');
    await t.asService(
      `insert into coach_athlete_links (coach_id, athlete_id, status) values ($1,$2,'ended')`,
      [coachA, past]);
    await assert.rejects(
      () => notify([coachA, 'alert', 'attention', 'Past', 'body', '/coach',
        'ended:1', past, 'checkin_flagged', null, ['in_app']]),
      /roster/i);
  });
});

describe('saying it once', () => {
  it('suppresses the same news rather than raising', async () => {
    const key = `soreness_reported:${athleteA}:2026-08-24`;
    const first = await notify([coachA, 'alert', 'attention', 'Athlete A — reported a niggle',
      'Reported: left calf tight.', '/coach', key, athleteA, 'soreness_reported', null, ['in_app']]);
    const again = await notify([coachA, 'alert', 'attention', 'Reworded, same news',
      'Reported: left calf tight.', '/coach', key, athleteA, 'soreness_reported', null, ['in_app']]);

    assert.ok(first.rows[0].id);
    assert.equal(again.rows[0].id, null, 'suppressed, not an error');

    const { rows } = await t.asService(
      `select count(*)::int n from notifications where dedupe_key = $1`, [key]);
    assert.equal(rows[0].n, 1);
  });

  it('lets two coaches each be told about their own athlete', async () => {
    // the dedupe is per coach, so a shared key never silences the second one
    const key = 'shared-key:2026-08-24';
    const a = await notify([coachA, 'digest', 'information', 'A', 'body', '/coach', key,
      null, null, null, ['in_app']]);
    const b = await notify([coachB, 'digest', 'information', 'B', 'body', '/coach', key,
      null, null, null, ['in_app']]);
    assert.ok(a.rows[0].id && b.rows[0].id, 'both written');
  });

  it('treats next week\'s check-in as new news', async () => {
    const later = await notify([coachA, 'alert', 'attention', 'Athlete A — reported a niggle',
      'Reported: still tight.', '/coach', `soreness_reported:${athleteA}:2026-08-31`,
      athleteA, 'soreness_reported', null, ['in_app']]);
    assert.ok(later.rows[0].id);
  });
});

describe('who can read a feed', () => {
  it('shows a coach their own and nobody else\'s', async () => {
    const mine = await t.asUser(coachA, `select count(*)::int n from notifications`);
    const theirs = await t.asUser(coachB, `select count(*)::int n from notifications`);
    const all = await t.asService(`select count(*)::int n from notifications`);

    assert.ok(mine.rows[0].n > 0);
    assert.ok(all.rows[0].n > mine.rows[0].n, 'there is more in the table than coach A can see');
    assert.equal(theirs.rows[0].n, 1, 'coach B sees only their own digest');
  });

  it('shows an athlete none of what was said about them', async () => {
    const { rows } = await t.asUser(athleteA,
      `select count(*)::int n from notifications where athlete_id = $1`, [athleteA]);
    assert.equal(rows[0].n, 0, 'a coach\'s feed is not the athlete\'s to read');
  });

  it('shows an outsider nothing at all', async () => {
    const { rows } = await t.asUser(outsider, `select count(*)::int n from notifications`);
    assert.equal(rows[0].n, 0);
  });

  it('lets a coach mark their own read, and nobody else\'s', async () => {
    const { rows } = await t.asService(
      `select id from notifications where user_id = $1 limit 1`, [coachA]);
    const id = rows[0].id;

    await t.asUser(coachA, `select im_notification_state($1,'read')`, [id]);
    const after = await t.asService(`select state, read_at from notifications where id = $1`, [id]);
    assert.equal(after.rows[0].state, 'read');
    assert.ok(after.rows[0].read_at, 'and stamped when');

    // coach B calling it on coach A's notification silently changes nothing
    await t.asUser(coachB, `select im_notification_state($1,'dismissed')`, [id]);
    const untouched = await t.asService(`select state from notifications where id = $1`, [id]);
    assert.equal(untouched.rows[0].state, 'read');
  });
});

describe('deliveries', () => {
  it('queues one row per configured channel', async () => {
    const { rows } = await notify([coachA, 'digest', 'information', 'Two channels', 'body', '/coach',
      'two-channel:1', null, null, null, ['in_app', 'email']]);
    const del = await t.asService(
      `select channel, state from notification_deliveries where notification_id = $1 order by channel`,
      [rows[0].id]);

    // ordered by the enum, not alphabetically: in_app is declared first
    assert.deepEqual(del.rows.map((r) => r.channel), ['in_app', 'email']);
    assert.ok(del.rows.every((r) => r.state === 'pending'), 'nothing is delivered until it is');
  });

  it('refuses a stranger forging a delivery receipt', async () => {
    const { rows } = await t.asService(
      `select id from notification_deliveries where state = 'pending' limit 1`);
    const message = await t.expectRefused(outsider,
      `select im_record_delivery($1,'delivered','forged')`, [rows[0].id]);
    assert.match(message ?? '', /delivery worker/i);

    const after = await t.asService(
      `select state, detail from notification_deliveries where id = $1`, [rows[0].id]);
    assert.equal(after.rows[0].state, 'pending', '"delivered" still means something');
    assert.equal(after.rows[0].detail, null);
  });

  it('refuses the recipient forging their own receipt', async () => {
    const { rows } = await t.asService(
      `select id from notification_deliveries where user_id = $1 and state = 'pending' limit 1`, [coachA]);
    const message = await t.expectRefused(coachA,
      `select im_record_delivery($1,'delivered','me')`, [rows[0].id]);
    assert.ok(message, 'not even the person it is for');
  });

  it('records an outcome, its reason and the attempt count', async () => {
    const { rows } = await t.asService(
      `select id from notification_deliveries where state = 'pending' limit 1`);
    await t.asService(`select im_record_delivery($1,'unavailable','email is not configured.')`, [rows[0].id]);

    const after = await t.asService(
      `select state, detail, attempts, attempted_at, delivered_at
         from notification_deliveries where id = $1`, [rows[0].id]);
    assert.equal(after.rows[0].state, 'unavailable');
    assert.match(after.rows[0].detail, /not configured/);
    assert.equal(after.rows[0].attempts, 1);
    assert.ok(after.rows[0].attempted_at, 'when it was tried');
    assert.equal(after.rows[0].delivered_at, null, 'unavailable is not delivered');
  });

  it('stamps delivered_at only on delivery', async () => {
    const { rows } = await notify([coachA, 'digest', 'information', 'Delivered', 'body', '/coach',
      'delivered:1', null, null, null, ['in_app']]);
    const del = await t.asService(
      `select id from notification_deliveries where notification_id = $1`, [rows[0].id]);
    await t.asService(`select im_record_delivery($1,'delivered','Shown in Iron Miles.')`, [del.rows[0].id]);

    const after = await t.asService(
      `select state, delivered_at from notification_deliveries where id = $1`, [del.rows[0].id]);
    assert.equal(after.rows[0].state, 'delivered');
    assert.ok(after.rows[0].delivered_at);
  });

  it('lets a coach see how their own notifications were delivered', async () => {
    const { rows } = await t.asUser(coachA, `select count(*)::int n from notification_deliveries`);
    assert.ok(rows[0].n > 0, 'their own delivery log is theirs to read');

    const others = await t.asUser(coachB,
      `select count(*)::int n from notification_deliveries where user_id = $1`, [coachA]);
    assert.equal(others.rows[0].n, 0);
  });
});

describe('preferences', () => {
  it('lets a coach set and read their own', async () => {
    await t.asUser(coachA,
      `insert into notification_preferences (user_id, digest_hour, timezone, quiet_from, quiet_until)
       values ($1, 6, 'Europe/Dublin', 22, 7)
       on conflict (user_id) do update set digest_hour = excluded.digest_hour`, [coachA]);

    const { rows } = await t.asUser(coachA,
      `select digest_hour, timezone, digest_enabled, channels from notification_preferences where user_id = $1`,
      [coachA]);
    assert.equal(rows[0].digest_hour, 6);
    assert.equal(rows[0].timezone, 'Europe/Dublin');
    assert.equal(rows[0].digest_enabled, true, 'the default is on');
    assert.deepEqual(rows[0].channels, ['in_app']);
  });

  it('refuses a coach writing another coach\'s preferences', async () => {
    const message = await t.expectRefused(coachB,
      `insert into notification_preferences (user_id, digest_hour) values ($1, 3)`, [coachA]);
    assert.ok(message, 'quiet hours are not something someone else sets for you');

    const { rows } = await t.asService(
      `select digest_hour from notification_preferences where user_id = $1`, [coachA]);
    assert.equal(rows[0].digest_hour, 6, 'unchanged');
  });

  it('shows a coach nobody else\'s preferences', async () => {
    const { rows } = await t.asUser(coachB,
      `select count(*)::int n from notification_preferences where user_id = $1`, [coachA]);
    assert.equal(rows[0].n, 0);
  });

  it('holds the digest date so the hour rolling round does not send it twice', async () => {
    await t.asService(
      `update notification_preferences set last_digest_local_date = '2026-08-27' where user_id = $1`, [coachA]);
    const { rows } = await t.asUser(coachA,
      `select last_digest_local_date from notification_preferences where user_id = $1`, [coachA]);
    assert.equal(rows[0].last_digest_local_date.toISOString().slice(0, 10), '2026-08-27');
  });
});

describe('the job\'s view of the roster', () => {
  it('lets the service role read the roster it is summarising', async () => {
    const { rows } = await t.asService(
      `select athlete_id from im_coach_roster($1, current_date)`, [coachA]);
    assert.ok(rows.some((r) => r.athlete_id === athleteA),
      'without this every digest would be silently empty and the job would report success');
    assert.ok(!rows.some((r) => r.athlete_id === athleteB), 'and only that coach\'s');
  });

  it('still gives a coach their own roster when they ask for another\'s', async () => {
    const { rows } = await t.asUser(coachA,
      `select athlete_id from im_coach_roster($1, current_date)`, [coachB]);
    assert.ok(!rows.some((r) => r.athlete_id === athleteB), 'the link table is the authority');
  });

  it('gives an athlete no roster at all', async () => {
    const { rows } = await t.asUser(athleteA,
      `select count(*)::int n from im_coach_roster(null, current_date)`);
    assert.equal(rows[0].n, 0);
  });
});
